//! Test-only helpers for the sync module (DESIGN §13.3). Builds an in-memory DB
//! that carries the REAL application schema (exported from the JS migration
//! registry into `tests/fixtures/schema_full.sql`), then layers the sync schema
//! on top. The module is gated with `#[cfg(test)]` at its declaration in
//! `sync/mod.rs`, so it never ships in the binary.

use rusqlite::Connection;

use crate::sync::schema::ensure_sync_schema;

/// The checked-in schema fixture: the concatenation of every JS migration's SQL
/// plus the programmatic layouts DDL. Generated by
/// `packages/store/scripts/export-schema.mjs`; a vitest test asserts it stays in
/// sync with the registry.
pub const SCHEMA_FIXTURE: &str = include_str!("../../tests/fixtures/schema_full.sql");

/// Opens an in-memory DB configured like a real sync connection and loads the
/// full application schema fixture. Does NOT install sync triggers — call
/// [`crate::sync::capture::ensure_capture`] for that.
pub fn new_app_schema_db() -> Connection {
    let conn = Connection::open_in_memory().expect("open in-memory db");
    conn.execute_batch(
        "PRAGMA journal_mode=MEMORY; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;",
    )
    .expect("configure pragmas");
    conn.execute_batch(SCHEMA_FIXTURE)
        .expect("apply schema fixture");
    conn
}

/// Like [`new_app_schema_db`] but also ensures the sync schema is present, ready
/// for capture/trigger tests.
pub fn new_synced_test_db() -> Connection {
    let conn = new_app_schema_db();
    ensure_sync_schema(&conn).expect("ensure sync schema");
    conn
}

fn meta_set(conn: &Connection, key: &str, value: &str) {
    conn.execute(
        "INSERT INTO sync_meta(key, value) VALUES (?1, ?2)
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        rusqlite::params![key, value],
    )
    .expect("write sync_meta");
}

/// Marks a sync session as configured (sets `device_id`) without enabling
/// capture — mirrors the post-login, pre-`capture_enabled` window.
pub fn set_session(conn: &Connection) {
    meta_set(conn, "device_id", "test-device");
}

/// Configures a session AND enables capture (`device_id` + `capture_enabled=1`).
pub fn set_session_with_capture(conn: &Connection) {
    set_session(conn);
    meta_set(conn, "capture_enabled", "1");
}

/// Total rows in `sync_oplog`.
pub fn oplog_count(conn: &Connection) -> i64 {
    conn.query_row("SELECT COUNT(*) FROM sync_oplog", [], |row| row.get(0))
        .expect("count oplog")
}

/// Rows in `sync_oplog` for a given table.
pub fn oplog_count_for(conn: &Connection, table: &str) -> i64 {
    conn.query_row(
        "SELECT COUNT(*) FROM sync_oplog WHERE table_name = ?1",
        [table],
        |row| row.get(0),
    )
    .expect("count oplog for table")
}

/// Number of installed `trg_sync_*` triggers.
pub fn trg_sync_count(conn: &Connection) -> i64 {
    conn.query_row(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='trigger' AND name LIKE 'trg_sync_%'",
        [],
        |row| row.get(0),
    )
    .expect("count sync triggers")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_creates_all_synced_base_tables() {
        let conn = new_app_schema_db();
        for table in crate::sync::capture::SYNCED_TABLES {
            let exists: bool = conn
                .query_row(
                    "SELECT 1 FROM sqlite_master WHERE type='table' AND name = ?1",
                    [table],
                    |_| Ok(true),
                )
                .unwrap_or(false);
            assert!(exists, "fixture is missing synced table {table}");
        }
    }

    #[test]
    fn fixture_includes_generated_search_text_and_fts() {
        let conn = new_app_schema_db();
        // items.search_text is a GENERATED column (DESIGN §2) — inserting without
        // it must succeed and the column must be present + hidden in table_xinfo.
        conn.execute(
            "INSERT INTO items(id,title,collection_id,created_at,updated_at)
             SELECT 'i1','T', c.id, 1, 1 FROM (SELECT 'c1' AS id) c
             WHERE 1=1",
            [],
        )
        .ok();
        let fts_exists: bool = conn
            .query_row(
                "SELECT 1 FROM sqlite_master WHERE name='fts_items'",
                [],
                |_| Ok(true),
            )
            .unwrap_or(false);
        assert!(
            fts_exists,
            "fixture should create the fts_items virtual table"
        );
    }
}
